### ISSUE TITLE
build error: compiled using NODE_MODULE 64 requires NODE_MODULE 87 

### ISSUE THREAD

**Issue by newcanopies** [sourjyadip/ROVDashboard#9]
Hi, on WSL2 running Ubuntu 20.4 with ROS2 Foxy I get the following errors:

```
npm start

> test@1.0.0 start /home/ROVDashboard
> electron .

App threw an error during load
Error: The module '/home/ROVDashboard/node_modules/rclnodejs/build/Release/rclnodejs.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 87. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1846)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (/home/ROVDashboard/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/home/ROVDashboard/node_modules/rclnodejs/lib/clock.js:17:38)
```

and a libva error (which may be due to the NVIDIA graphics incompatibility)
`libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)`

Tried with node versions v10.23.1 and v12.20.1:

npm   uninstall rclnodejs
npm rebuild rclnodejs   --update-binary
npm cache   clean --force
rm -rf node_modules
rm -rf package-lock.json
npm i 
npm start -> same error as above

Cheers

**Comment by purvikpatel** [comment]
You will have to rebuild modules for electron.  Use this link to solve the error.

https://www.electronjs.org/docs/tutorial/using-native-node-modules

**Comment by newcanopies** [comment]
Thank you @purvikpatel, I do not have a global install of electron but `electron-rebuild` succeeded.

**Comment by purvikpatel** [comment]
@newcanopies  Not really. I am actually new to node.js and electron. I researched a bit and came to conclusion that this would be best for our application. if you have any suggestions for improvement please let me know.
